## In this notebook we are to cover some of the most fundamental concepts of tensorflow
WE ARE GOING TO COVER
* Introduction to tensors
* Getting info from the tensors
* Manipulating tensors
* Tensors & NumPy
* Using @tf.function
* Using GPU(In my case I am basically using CPU(i.e.I got AMD Graphics Card))

### Introduction to Tensors

In [1]:
import tensorflow as tf
tf.__version__

'2.16.1'

In [2]:
# Create tensors with tf.constant()
scalar=tf.constant(5)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [3]:
#Check the number of dimensions of a tensor(ndim stands for the number of dimensions)
scalar.ndim

0

In [4]:
# Create a vector
vector=tf.constant([69,69])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([69, 69])>

In [5]:
#Check the dimensions of vector
vector.ndim

1

In [6]:
#Create a matrix(It will have more than one dimensions)
matrix=tf.constant([[89,789],
                  [879,29]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89, 789],
       [879,  29]])>

In [7]:
matrix.ndim

2

In [8]:
#Create an another matrix with a data type
matrix1=tf.constant([[12312.12,79],
                     [1233,23],
                    [2312,434]],dtype=tf.float16)
matrix1

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[12312.,    79.],
       [ 1233.,    23.],
       [ 2312.,   434.]], dtype=float16)>

In [9]:
matrix1.ndim

2

In [10]:
#Lets create a tensor
tensor=tf.constant([[[1,2,3],
                     [4,5,6]],
                     [[7,8,9],
                     [10,11,12]],
                     [[13,14,15],
                     [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [11]:
tensor.ndim

3

What we have created so far:

* Scalar: a single number
* Vector: a number with a direction(e.g.wind speed and direction)
* Matrix: a 2-dimensional array of number
* Tensor: an n-dimensional array of numbers(a 0 dimensional tensor is a scalar and a 1 dimensional tensor is a vector)


### Creating tensors with tf.variable

In [12]:
# Create the smae tensor with same tf.variable as above
changable_tensor=tf.Variable([10,45])
unchangable_tensor=tf.constant([10,45])
unchangable_tensor,changable_tensor

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 45])>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 45])>)

In [13]:
# Let's try to change the numbers in the changable tensor
changable_tensor[0]=34
changable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [14]:
# We have to use the function .assign()
changable_tensor[0].assign(4)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 4, 45])>

In [15]:
#Now let's try to change the elements in the unchangale tensor
unchangable_tensor[0].assign(0)
unchangable_tensor
# So we cannot change the elements in the tf.constant()

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

### Creating random tensors

A Random Tensor is a tensor of some arbitary size which contain random numbers

In [16]:
# Create two Random Tensors
random_1=tf.random.Generator.from_seed(43)# set a seed for reproducibility
random_1=random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(43)
random_2=random_2.normal(shape=(3,2))
random_1,random_2,random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646],
        [-0.7535805 , -0.57166284]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646],
        [-0.7535805 , -0.57166284]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in the tensor

In [17]:
# Shuffle a tensor(valuable for when a person want to shuffle the dat aso the inherent order does'nt matter)
not_shuffled=tf.constant([[10,7],
                          [42,42],
                          [423,6]])
# Shuffle or non-shuffled tensor
tf.random.shuffle(not_shuffled,seed=43)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 10,   7],
       [423,   6],
       [ 42,  42]])>

In [18]:
#Shuffle our non-shuffled tensor
tf.random.set_seed(42) # Global level random seed
tf.random.shuffle(not_shuffled,seed=42) # Operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 10,   7],
       [ 42,  42],
       [423,   6]])>

In [19]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 10,   7],
       [ 42,  42],
       [423,   6]])>

**Excercise:** Read through TensorFlow Documentation on random sedd generation and practise writing 5 random tensors and shuffle them

> If we want our shuffled tensor to be in the same order then we have to set both the global and operational level random seed to the *same number*

In [20]:
random_3=tf.random.Generator.from_seed(69)
random_3=random_3.normal(shape=(3,3))
random_3

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.29164317,  1.4531525 , -0.8223833 ],
       [-1.3446563 , -0.7183838 , -0.20373915],
       [ 0.6291725 , -0.87623316, -0.5923522 ]], dtype=float32)>

In [21]:
#Now Shuffling the generated random tensor
tf.random.set_seed(69)
tf.random.shuffle(random_3,seed=69)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.6291725 , -0.87623316, -0.5923522 ],
       [ 0.29164317,  1.4531525 , -0.8223833 ],
       [-1.3446563 , -0.7183838 , -0.20373915]], dtype=float32)>

In [22]:
# Now generating another random tensor and shuffling it using the tf.shuffle() function
random_4=tf.random.Generator.from_seed(45)
random_4=random_4.normal(shape=(4,5))
random_4

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[-0.3522796 ,  0.40621263, -1.0523509 ,  1.2054597 ,  1.6874489 ],
       [-0.4462975 , -2.3410842 ,  0.99009085, -0.0876323 , -0.635568  ],
       [-0.6161736 , -1.9441465 , -0.48293006, -0.52447474, -1.0345329 ],
       [ 1.3066901 , -1.5184573 , -0.4585211 ,  0.5714663 , -1.5331722 ]],
      dtype=float32)>

In [23]:
# Now Shuffling the generated random tensor random_4
tf.random.set_seed(45)
tf.random.shuffle(random_4,seed=45)

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[ 1.3066901 , -1.5184573 , -0.4585211 ,  0.5714663 , -1.5331722 ],
       [-0.4462975 , -2.3410842 ,  0.99009085, -0.0876323 , -0.635568  ],
       [-0.6161736 , -1.9441465 , -0.48293006, -0.52447474, -1.0345329 ],
       [-0.3522796 ,  0.40621263, -1.0523509 ,  1.2054597 ,  1.6874489 ]],
      dtype=float32)>

In [24]:
# Now creating another tensor by using the random function and shuffling it
random_5=tf.random.Generator.from_seed(78)
random_5=random_5.normal(shape=(5,5))
random_5

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-1.4084325 , -1.8613014 ,  1.0928144 , -0.29996362, -0.7382552 ],
       [ 1.2053189 , -0.3511434 ,  0.13897082,  0.32744762, -0.3579723 ],
       [ 1.230323  , -0.13087   , -0.44519424,  0.9551449 ,  0.24270573],
       [-0.02293015, -0.97063404, -0.7102746 ,  0.4939478 ,  2.1883757 ],
       [-0.4953925 , -0.7584407 ,  0.13736533, -0.44198883, -0.65641224]],
      dtype=float32)>

In [25]:
#Now shuffling the generated random tensor
tf.random.set_seed(89)
tf.random.shuffle(random_5,89)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.02293015, -0.97063404, -0.7102746 ,  0.4939478 ,  2.1883757 ],
       [-0.4953925 , -0.7584407 ,  0.13736533, -0.44198883, -0.65641224],
       [ 1.230323  , -0.13087   , -0.44519424,  0.9551449 ,  0.24270573],
       [-1.4084325 , -1.8613014 ,  1.0928144 , -0.29996362, -0.7382552 ],
       [ 1.2053189 , -0.3511434 ,  0.13897082,  0.32744762, -0.3579723 ]],
      dtype=float32)>

### Other ways to make tensors

In [26]:
# Create a tensor of all ones
tf.ones([2,4])

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [27]:
# Create a tensor in all zeros
tf.zeros(shape=(4,3))

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors

The main difference between NumPy and Tensorflow tensors is that tensors can be run on a GPU for faster computing

In [28]:
# You can also turn NumPy arrays into tensors
import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [29]:
A=tf.constant(numpy_A,shape=(2,3,4))#1st Number:Tells number of sub matrices,2nd Number:Tells the number of rows,3rd Number:Tells the number of columns
B=tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>)

In [30]:
A.ndim

3

### Getting Information from the Tensors
* Shape : The length(no. of elements) of each of the dimensions of a tensor
* Rank : The number oftensor dimensions.A scalar has a rank 0 and a vector has a rank 1
* Axis or Dimension : A particular dimension of a tensor
* Size : The total number of items in a tensor

In [31]:
# Create a tensor wth rank=4(4 dimensions)
rank_4_tensor=tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [32]:
rank_4_tensor.ndim

4

In [33]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [34]:
rank_4_tensor[1]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [35]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [36]:
2*3*4*5

120

In [37]:
# Get various attributes of our tensors
print("Datatype of every element:",rank_4_tensor.dtype)
print("Number of dimensions(Rank):",rank_4_tensor.ndim)
print("Shape of tensor:",rank_4_tensor.shape)
print("Elements along 0 axis:",rank_4_tensor.shape[0])
print("Elements along the last axis:",rank_4_tensor.shape[-1])
print("Total number of elements in our tensor",tf.size(rank_4_tensor))

Datatype of every element: <dtype: 'float32'>
Number of dimensions(Rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor tf.Tensor(120, shape=(), dtype=int32)


### Indexing Tensors
Tensors can be indexed just like python Lists

In [38]:
some_list=[1,2,3,4]
some_list[:2]

[1, 2]

In [39]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [40]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [41]:
some_list[:1]

[1]

In [42]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [43]:
# Get each first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [44]:
# Create a rank 2 tensor(2 dimensions)
rank_2_tensor=tf.constant([[10,7],
                           [3,4]])
rank_2_tensor.shape,rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [45]:
# Get the last item of each roe of our 2D Tensor
rank_2_tensor[:,-1] # Here the ':' represents the value for the first axis i.e. for ROWS

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

#### Add in extra dimension to our tensor

In [46]:
rank_3_tensor=rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [47]:
# Alternative for tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1) #"-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

### Manipulating Tensors(Tensor Operations)
**Basic Operations**

In [48]:
# You can add values to a tensor using the addition operator
tensor=tf.constant([[10,7],
                    [12,34]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [22, 44]])>

In [49]:
# The Original tensor is unchange
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [12, 34]])>

In [50]:
# Multiplication also works
tensor*100

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1000,  700],
       [1200, 3400]])>

In [51]:
# Substraction
tensor-12

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-2, -5],
       [ 0, 22]])>

In [52]:
# We can use the tensorflow bulit in function too
tf.multiply(tensor,18391083)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[183910830, 128737581],
       [220692996, 625296822]])>

In [53]:
# The division is also similar to regular numbers
tensor/10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [1.2, 3.4]])>

**Matrix Multiplication**:

In the world of tensors the matrix multiplication is one of the most common operation

There are two rules our tensors need to fullfill if we are foing to matrix multiply them:
1. The Inner dimensions must match
2. The resulting matrix has the shape of the outer dimensions

In [54]:
# MAtrix Multiplication in TensorFlow
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 184,  308],
       [ 528, 1240]])>

In [55]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [12, 34]])>

In [56]:
tensor*tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 100,   49],
       [ 144, 1156]])>

In [57]:
M_1=tf.constant([[1,2,5],
              [7,2,1],
              [3,3,3]])
M_2=tf.constant([[3,5],
               [6,7],
               [1,8]])
M_1,M_2

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]])>)

In [58]:
tf.matmul(M_1,M_2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]])>

In [59]:
# Matrix Multipliction with the python operator "@"
M_1 @ M_2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]])>

In [60]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 184,  308],
       [ 528, 1240]])>

In [61]:
# Create a tensor (3,2) tensor
X=tf.constant([[1,2],
              [3,4],
              [5,6]])
Y=tf.constant([[7,8],
              [9,10],
              [11,12]])
X,Y


(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [62]:
X @ Y

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [63]:
# Lets change th shape of Y
tf.reshape(Y,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]])>

In [64]:
# Try to matrix multiply X by reshaped Y
X @ tf.reshape(Y,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [65]:
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [66]:
tf.matmul(tf.reshape(X,shape=(2,3)),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]])>

In [67]:
# Can do the same with the transpose
tf.transpose(X),tf.reshape(X,shape=(2,3))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]])>)

In [68]:
# Matrix Multiplication with transpose rather than reshape
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

In [69]:
"""This clearly differentiates the differences between 
transpose and the reshape functions"""
Y,tf.transpose(Y),tf.reshape(Y,shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  9, 11],
        [ 8, 10, 12]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]])>)

**The Dot Product**

You can perform matrix multiplication using:
* `tf.matmul()`
* `tf.tensordot()`

In [70]:
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [71]:
# Perform the dot product on X and Y (requires X or Y to be transposed)
tf.tensordot(tf.transpose(X),Y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

**All the three functions does the same thing**

* `@`
* `tf.matmul`
* `tf.tensordot`

In [72]:
X @ tf.reshape(Y,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [73]:
tf.tensordot(X,tf.reshape(Y,shape=(2,3)),axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [74]:
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [75]:
# Peerform matrix multiplication between X and Y (transposed)
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

In [76]:
# Perform matrix multiplication of X and Y (reshaped)
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [77]:
# Check the value of Y, reshape Y and transposed Y
print("Normal Y")
print(Y,"\n") #"\n is for new line"

print("Y reshaped to (2,3)")
print(tf.reshape(Y,(2,3)),"\n")

print("Y transposed")
print(tf.transpose(Y),"\n")

Normal Y
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3)
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32) 



Generally,when performing matrix multiplication on two tensors and once one of the axes does'nt line up,you willtranspose(rather than reshape) one of the tensors to get satisfy the matrix multiplication

### Changing the datatype of the tensor 

In [78]:
# Create a new tensor with default datatype(float 32)
B =tf.constant([1.32,43.2])
B.dtype

tf.float32

In [79]:
C =tf.constant([1,2])
C.dtype

tf.int32

In [80]:
# Change from float 32 to float 16(Reduced Precision)
B= tf.cast(B,dtype=tf.float16)
B,B.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 1.32, 43.2 ], dtype=float16)>,
 tf.float16)

In [81]:
D =tf.cast(B,dtype=tf.float32)
D,D.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 1.3203125, 43.1875   ], dtype=float32)>,
 tf.float32)

In [82]:
# Change from int32 to float32
E=tf.cast(C,dtype=tf.float32)
E,E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>,
 tf.float32)

In [83]:
E_float16=tf.cast(E,dtype=tf.float16)
E_float16,E_float16.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 2.], dtype=float16)>,
 tf.float16)

### Aggregating the Tensors

Aggregating tensors is condesing them from multiple values down to a smaller amount of values

In [84]:
# Get the absolute values
D=tf.constant([-12,-3])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-12,  -3])>

In [85]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([12,  3])>

Let's go through the following forms of aggregation
* Get the maximum
* Get the minimum
* Get the mean of the tensor
* Get the sum of the tensor

In [86]:
# Creating a random tensor with values between 0 and 100  of size 50
E=tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([88, 66,  6, 34, 32, 61, 46, 50, 48, 82, 61, 96, 48, 53, 23, 23, 30,
       67, 76, 20, 68, 22, 58, 48, 92, 10, 93, 31, 34, 57, 80, 10, 31, 30,
       22, 30, 54, 95, 73, 26, 94, 99, 98, 32, 43, 12, 44, 56, 57, 46])>

In [87]:
tf.size(E),E.ndim,E.shape

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, 1, TensorShape([50]))

In [88]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [89]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=99>

In [90]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=51>

In [91]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2555>

In [92]:
# Find the variance
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=690.69>

In [93]:
# Find the standard deviation
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=26.280981>

In [94]:
tf.math.reduce_variance(tf.cast(D,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=20.25>

### Find the positional maximum and minimum



In [95]:
# Create a new tensor for finding positional maximum and minimum
tf.random.set_seed(23)
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.43993807, 0.09729016, 0.8235066 , 0.22273934, 0.3318541 ,
       0.25352108, 0.34313524, 0.45672834, 0.60538435, 0.46301937,
       0.50474167, 0.5150137 , 0.5610179 , 0.13842285, 0.9624418 ,
       0.5469624 , 0.98602736, 0.7543844 , 0.19885683, 0.991691  ,
       0.47549224, 0.17814577, 0.89089394, 0.24397457, 0.85176086,
       0.8440089 , 0.7800995 , 0.07725966, 0.2982911 , 0.57528853,
       0.2866801 , 0.6147386 , 0.64163256, 0.90662575, 0.01245236,
       0.4213121 , 0.91082525, 0.27526963, 0.68104875, 0.50922835,
       0.20153081, 0.29233146, 0.43840623, 0.9122982 , 0.87145627,
       0.47187352, 0.20997441, 0.5697775 , 0.59673095, 0.42037487],
      dtype=float32)>

In [96]:
# Finding the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=19>

In [97]:
# index on our largest value postion
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.991691>

In [98]:
# Find the maximum value of F tensor
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.991691>

In [99]:
# Check for equality
F[tf.argmax(F)]==tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [100]:
# Find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=34>

In [101]:
# Find the minimum using the positional minimum index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.012452364>

In [102]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.012452364>

### Squeezing a tensor(REmoving all single dimensions)

In [103]:
# Create a tensor to get started
tf.random.set_seed(23)
G=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.43993807, 0.09729016, 0.8235066 , 0.22273934, 0.3318541 ,
           0.25352108, 0.34313524, 0.45672834, 0.60538435, 0.46301937,
           0.50474167, 0.5150137 , 0.5610179 , 0.13842285, 0.9624418 ,
           0.5469624 , 0.98602736, 0.7543844 , 0.19885683, 0.991691  ,
           0.47549224, 0.17814577, 0.89089394, 0.24397457, 0.85176086,
           0.8440089 , 0.7800995 , 0.07725966, 0.2982911 , 0.57528853,
           0.2866801 , 0.6147386 , 0.64163256, 0.90662575, 0.01245236,
           0.4213121 , 0.91082525, 0.27526963, 0.68104875, 0.50922835,
           0.20153081, 0.29233146, 0.43840623, 0.9122982 , 0.87145627,
           0.47187352, 0.20997441, 0.5697775 , 0.59673095, 0.42037487]]]]],
      dtype=float32)>

In [104]:
G.ndim

5

In [105]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [106]:
G_squeezed=tf.squeeze(G)
G_squeezed,G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.43993807, 0.09729016, 0.8235066 , 0.22273934, 0.3318541 ,
        0.25352108, 0.34313524, 0.45672834, 0.60538435, 0.46301937,
        0.50474167, 0.5150137 , 0.5610179 , 0.13842285, 0.9624418 ,
        0.5469624 , 0.98602736, 0.7543844 , 0.19885683, 0.991691  ,
        0.47549224, 0.17814577, 0.89089394, 0.24397457, 0.85176086,
        0.8440089 , 0.7800995 , 0.07725966, 0.2982911 , 0.57528853,
        0.2866801 , 0.6147386 , 0.64163256, 0.90662575, 0.01245236,
        0.4213121 , 0.91082525, 0.27526963, 0.68104875, 0.50922835,
        0.20153081, 0.29233146, 0.43840623, 0.9122982 , 0.87145627,
        0.47187352, 0.20997441, 0.5697775 , 0.59673095, 0.42037487],
       dtype=float32)>,
 TensorShape([50]))

### One Hot Encoding Tensors

In [107]:
# Create a list indices
some_list=[0,1,2,3] # could be red,green,blue and purple

# One hot encode for our list of indices
tf.one_hot(some_list,depth=4)


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [108]:
# Specify custom values for one hot encoding
tf.one_hot(some_list,depth=4,on_value="Yo!",off_value="Luffy")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Yo!', b'Luffy', b'Luffy', b'Luffy'],
       [b'Luffy', b'Yo!', b'Luffy', b'Luffy'],
       [b'Luffy', b'Luffy', b'Yo!', b'Luffy'],
       [b'Luffy', b'Luffy', b'Luffy', b'Yo!']], dtype=object)>

### Squaring,Log and Square Root

In [109]:
# Create a new tensor
H=tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [110]:
# Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [111]:
# Square root(This method requires non int type)
H=tf.cast(H,dtype=tf.float32)
tf.math.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [112]:
# Find the Logarithm
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy

Tensorflow interacts beautifully with NumPy array

In [113]:
# Create a tensor directly with NumPy array
J=tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [114]:
# Convert our tensor back to a NumPy array
np.array(J),type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [115]:
# Convert tensor J to a NumPy array(EASY WAY)
J.numpy(),type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [116]:
# The default types of each are slightly different
numpy_J=tf.constant(np.array([3.,4.,5.]))
tensor_J=tf.constant([3.,4.,7.])
# Check the datatypes of each 
numpy_J.dtype,tensor_J.dtype

(tf.float64, tf.float32)